on: [push, pull_request]

name: check

jobs:
  check:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} R ${{ matrix.r-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macOS-10.15, ubuntu-20.04, windows-2022 ]
        r-version: [ devel ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Install R
        uses: s-u/R-actions/install@v1
        with:
          r-version: ${{ matrix.r-version }}
          tools: base

      - uses: s-u/R-actions/pkg-check@master
        with:
          debian-deps: libssl-dev
          macos-deps: openssl-1.1.1p
          windows-deps: openssl
          check-flags: --as-cran
          dep-type: source
          build-script: sh mkdist
